#!/bin/bash -ex

# install needed packages for ansible 
yum install -y git ansible

#Get Producteev ansible playbook
git clone git@github.com:Producteev/ansible.git

echo "localhost ansible_connection=local" >> /etc/ansible/hosts

cd ./ansible
ansible-playbook main_env.yml -e "instance_role=web"

exit 0
