- name: Install Common Libraries from CentOS mirror
  yum:
   name: {{ item }}
   sate: present
  with_items:
   - vim
   - gcc
   - gcc-c++
   - autoconf
   - automake
   - libxml2-devel
   - unzip
   - zip
   - htop
   - wget
   - tar
   - tmpwatch
   - libenchant*
   - libcrypt*
   - sendmail-milter
   - unixODBC
   - net-snap   
   - freetds
   - freetds-devel
