---

- name: Swiftmailer job 1
  command: /usr/bin/php /var/www/producteev4/current/app/console swiftmailer:spool:send  --time-limit=59 --env=prod

- name: Swiftmailer job 2
  command: /usr/bin/php /var/www/producteev4/current/app/console swiftmailer:spool:send  --time-limit=59 --env=prod

- name: Mixpanel events job
  command: /usr/bin/php /var/www/producteev4/current/app/console mixpanel:events:send --max=2000 --env=prod

- name: Clear application cache.
  command: /usr/bin/php /var/www/producteev4/current/app/console cache:clear --no-warmup --env=prod

- name: Clear Mongo cache/Meta Data.
  command: /usr/bin/php /var/www/producteev4/current/app/console doctrine:mongodb:cache:clear-metadata --no-warmup --env=prod

- name: Update Mongo DB schema.
  command: /usr/bin/php /var/www/producteev4/current/app/console doctrine:mongodb:schema:update --no-warmup --env=prod

- name: Import Language.
  command: /usr/bin/php /var/www/producteev4/current/app/console producteev:lang:process

- name: JS Build 1.
  command: /usr/bin/php /var/www/producteev4/current/app/console producteev:js:build --uglify

- name: JS Build 2.
  command: /usr/bin/php /var/www/producteev4/current/app/console producteev:jivejs:build

- name: Assetic Dump.
  command: /usr/bin/php /var/www/producteev4/current/app/conole assetic:dump --env=prod

- name: Stop Scheduled Worker.
  command: /usr/bin/php /var/www/producteev4/current/app/conole producteev:worker --env=prod

- name: Start Scheduled Worker.
  command: /usr/bin/php /var/www/producteev4/current/app/conole producteev:worker --env=prod

- name: Stop Worker.
  command: /usr/bin/php /var/www/producteev4/current/app/conole producteev:worker --stop --env=prod

- name: Start Worker.
  command: /usr/bin/php /var/www/producteev4/current/app/conole producteev:worker --start --env=prod
