---

- name: Clone bitbucket repo
  git:
    repo: git@github.com:Producteev/producteev4.git
    dest: /var/www/producteev4
    version: worker-{{ instance_env }}
    accept_hostkey: yes
    key_file: ~/.ssh/id_rsa
  become_user: root

- name: Change permissions
  file: path=/var/www/producteev4 owner={{ httpd_user }} group={{ httpd_group }} mode=0775 state=directory recurse=yes

- name: Swiftmailer job 1
  command: /usr/bin/php /var/www/producteev4/app/console swiftmailer:spool:send  --time-limit=59 --env=prod

- name: Swiftmailer job 2
  command: /usr/bin/php /var/www/producteev4/app/console swiftmailer:spool:send  --time-limit=59 --env=prod

- name: Clear application cache.
  command: /usr/bin/php /var/www/producteev4/app/console cache:clear --no-warmup --env=prod

- name: Clear Mongo cache/Meta Data.
  command: /usr/bin/php /var/www/producteev4/app/console doctrine:cache:clear-metadata --no-warmup --env=prod

- name: Update Mongo DB schema.
  command: /usr/bin/php /var/www/producteev4/app/console doctrine:mongodb:schema:update --env=prod

- name: Import Language.
  command: /usr/bin/php /var/www/producteev4/app/console producteev:lang:process

- name: JS Build 1.
  command: /usr/bin/php /var/www/producteev4/app/console producteev:js:build --uglify

- name: JS Build 2.
  command: /usr/bin/php /var/www/producteev4/app/console producteev:jivejs:build

- name: Assetic Dump.
  command: /usr/bin/php /var/www/producteev4/app/console assetic:dump --env=prod

- name: Stop Scheduled Worker.
  command: /usr/bin/php /var/www/producteev4/app/console producteev:workers --stop-scheduled --env=prod

- name: Start Scheduled Worker.
  command: /usr/bin/php /var/www/producteev4/app/console producteev:workers --start-scheduled --env=prod

- name: Stop Worker.
  command: /usr/bin/php /var/www/producteev4/app/console producteev:worker --stop --env=prod

- name: Start Worker.
  command: /usr/bin/php /var/www/producteev4/app/console producteev:worker --start --env=prod
