---

- name: create vhost file for producteev
  template: src=producteev.conf dest=/etc/httpd/conf.d/producteev.conf owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd

- name: create vhost file for the blog
  template: src=blog-proxy.conf dest=/etc/httpd/conf.d/blog-proxy.conf owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd
