---

- name: create vhost file for producteev
  template: src=producteev4.conf dest=/etc/httpd/conf.d/producteev4.conf owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd

- name: create vhost file for the blog
  template: src=blog-proxy.conf dest=/etc/httpd/conf.d/dev-blog-proxy.conf owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd

- name: Setup SSL certificate file
  template: src=ssl/{{ item }} dest=/etc/httpd/ssl/{{ item }} mode=0600 owner={{ httpd_user }} group={{ httpd_group }}
  notify: restart apache
  with_items:
    - producteev.com.pem
    - producteev.com.key

- name: Clone Git Repository
  git: repo=git@github.com:Producteev/producteev4.git
       dest= {{ git_dest }}
       version: {{ branch }}

- name: Change permissions
  file: path=/var/www/producteev4 owner={{ httpd_user }} group={{ httpd_group }} mode=0775 state=directory recurse=yes


- name: Execute clear cache and update values.
  script: /var/www/producteev4/change-value.sh 
