---

- name: create vhost file for producteev
  template: src=producteev.conf dest=/etc/httpd/conf.d/producteev.conf owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd

- name: create vhost file for the blog
  template: src=blog-proxy.conf dest=/etc/httpd/conf.d/dev-blog-proxy.conf owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd

- name: Setup SSL certificate file
  template: src=ssl/{{ item }} dest=/etc/httpd/ssl/{{ item }} mode=0600 owner={{ httpd_user }} group={{ httpd_group }}
  notify: restart httpd
  with_items:
    - producteev.com.pem
    - producteev.com.key

- name: Clone GIT repo
  when: {{ instance_env }} == 'dev'
  git:
    repo: git@github.com:Producteev/producteev4.git
    dest: /var/www/producteev4
    version: automat-{{ instance_env }}
    accept_hostkey: yes
    key_file: ~/.ssh/id_rsa
  become_user: root

- name: Download from Nexus
  maven_artifact:
      group_id: producteev
      artifact_id: api
      extension: backup.tar.gz
      version: "{{ version }}"
      repository_url: 'http://54.91.36.184:8081/nexus/content/repositories/dev'
      username: "{{ nexus_user }}"
      password: "{{ nexus_password }}"
      dest: /opt/{{ version }}.tar.gz

- name: Extract Nexus file
  unarchive:
    src: /opt/api-{{ version }}.backup.tar.gz
    dest: /var/www

- name: Rename extracted folder
  command: mv /var/www/web-dev /var/www/producteev4

- name: Change permissions
  file: path=/var/www/producteev4 owner={{ httpd_user }} group={{ httpd_group }} mode=0775 state=directory recurse=yes

- name: Change-Value
  script: /var/www/producteev4/change-value.sh

- name: Clear application cache.
  command: /usr/bin/php /var/www/producteev4/app/console cache:clear --no-warmup --env=prod
