---

- name: create vhost file for producteev
  template: src=producteev.conf dest=/etc/httpd/conf.d/producteev.conf owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd

- name: create vhost file for the blog
  template: src=blog-proxy.conf dest=/etc/httpd/conf.d/dev-blog-proxy.conf owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd

- name: Setup SSL certificate file
  template: src=ssl/{{ item }} dest=/etc/httpd/ssl/{{ item }} mode=0600 owner={{ httpd_user }} group={{ httpd_group }}
  notify: restart httpd
  with_items:
    - producteev.com.pem
    - producteev.com.key

- name: Clone bitbucket repo
  git:
    repo: git@github.com:Producteev/producteev4.git
    dest: /var/www/producteev4
    version: automat-dev
    accept_hostkey: yes
    key_file: ~/.ssh/id_rsa
  become_user: root

- name: Install Composer
  composer: 
    command: install
    working_dir: /var/www/producteev4

- name: Change-Value
  script: /var/www/producteev4/change-value.sh

- name: Clear application cache.
  cron: name:"Clear App Cache" job="/usr/bin/php /var/www/producteev4/current/app/console cache:clear --no-warmup --env=dev" user=root 


- name: Change permissions
  file: path=/var/www/producteev4 owner={{ httpd_user }} group={{ httpd_group }} mode=0775 state=directory recurse=yes
