---

- name: create vhost file for producteev
  template: src=producteev.conf dest=/etc/httpd/conf.d/producteev.conf owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd

- name: create vhost file for the blog
  template: src=blog-proxy.conf dest=/etc/httpd/conf.d/dev-blog-proxy.conf owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd

- name: Setup SSL certificate file
  template: src=ssl/{{ item }} dest=/etc/httpd/ssl/{{ item }} mode=0600 owner={{ httpd_user }} group={{ httpd_group }}
  notify: restart httpd
  with_items:
    - producteev.com.pem
    - producteev.com.key

- name: Download from Nexus
  maven_artifact:
      group_id: producteev
      artifact_id: api
      extension: backup.tar.gz
      version: "{{ version }}"
      repository_url: 'http://54.91.36.184:8081/nexus/content/repositories/{{ instance_env }}'
      username: "{{ nexus_user }}"
      password: "{{ nexus_password }}"
      dest: /opt/{{ version }}.tar.gz

- name: Extract Nexus file
  unarchive:
    src: /opt/{{ version }}.tar.gz
    dest: /tmp

- name: Rename extracted folder
  command: cp -r /tmp/dev-web /var/www/producteev4

- name: create vhost file for the blog
  template: src={{ instance_env }}_hosts_production.yml dest=/var/www/producteev4/app/config/servers.d/production/hosts_production.yml owner={{ httpd_user }} group={{ httpd_group }} mode=0644
  notify: restart httpd

- name: Change permissions
  file: path=/var/www/producteev4 owner={{ httpd_user }} group={{ httpd_group }} mode=0775 state=directory recurse=yes

- name: Change-Value
  script: /var/www/producteev4/change-value.sh

- name: Clear application cache.
  command: /usr/bin/php /var/www/producteev4/app/console cache:clear --no-warmup --env=prod

- name: Delete Cache
  command: rm -rf /var/www/producteev4/cache/*

- name: Change permissions
  file: path=/var/www/producteev4 owner={{ httpd_user }} group={{ httpd_group }} mode=0775 state=directory recurse=yes
